version: '3.4'

services:
  #informed.application.reportingconsumer:
  #  image: "informedreportingconsumer:latest"
  #  depends_on:
  #    - db
  #    - messaging
  #  networks:
  #    - bridge

  # 10.0.75.1:3306 username-root pw-inf0rm3d
  # db:
    # image: "mysql:8"
    # environment:
      # MYSQL_ROOT_PASSWORD: "inf0rm3d"
    # volumes:
      # - //c/sqldata:/var/lib/mysql
    # ports:
      # - "3306:3306"
    # networks:
      # - bridge
  
  # http://10.0.75.1:15672/#/ user-admin pw-inf0rm3d!
  messaging:
    image: "rabbitmq:3-management"
    volumes:
      - ./rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config
      - ./rabbitmq/rabbitmq-definitions.json:/etc/rabbitmq/rabbitmq-definitions.json
    hostname: "scaling-test"
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - bridge

networks:
  bridge: {}